#include <iostream>
#include <fstream>
#include <map>
#include <string>


/**
This program analyzes text records generated by the Corner Grocer throughout the day, listing items purchased in chronological order from store opening to closing. It provides functionality to:

Prompt the user to input a specific item and return its frequency.
Print a list of all items purchased along with their frequencies.
Display a text-based histogram representing the frequencies of all items.
Create a data file for backing up the accumulated data.
Author: Julian Blanco
Date: 4/18/24
*/

class FrequencyTracker {
private:
    std::map<std::string, int> frequencyMap;

public:
    // Process the input file and update the frequency map
    void processFile(const std::string& filename) {
        std::ifstream inputFile(filename);
        if (!inputFile.is_open()) {
            std::cerr << "Error: Unable to open file: " << filename << std::endl;
            return;
        }

        std::string item;
        while (inputFile >> item) {
            frequencyMap[item]++;
        }

        inputFile.close();
    }

    // Get the frequency of a specific item
    int getFrequency(const std::string& item) const {
        if (frequencyMap.count(item)) {
            return frequencyMap.at(item);
        }
        else {
            return 0;
        }
    }

    // Print the list of item frequencies
    void printFrequencies() const {
        for (const auto& pair : frequencyMap) {
            std::cout << pair.first << " " << pair.second << std::endl;
        }
    }

    // Print a text-based histogram of item frequencies
    void printHistogram() const {
        for (const auto& pair : frequencyMap) {
            std::cout << pair.first << " ";
            for (int i = 0; i < pair.second; ++i) {
                std::cout << "*";
            }
            std::cout << std::endl;
        }
    }

    // Save the data to the output file
    void saveData(const std::string& filename) const {
        std::ofstream outputFile(filename);
        if (!outputFile.is_open()) {
            std::cerr << "Error: Unable to open file for writing: " << filename << std::endl;
            return;
        }

        for (const auto& pair : frequencyMap) {
            outputFile << pair.first << " " << pair.second << std::endl;
        }

        outputFile.close();
    }
};

int main() {
    FrequencyTracker tracker;
    tracker.processFile("CS210_Project_Three_Input_File.txt");

    int choice;
    do {
        std::cout << "\nMenu:\n";
        std::cout << "1. Look up frequency of a specific item\n";
        std::cout << "2. Print list of item frequencies\n";
        std::cout << "3. Print histogram of item frequencies\n";
        std::cout << "4. Exit\n";
        std::cout << "Enter your choice: ";
        std::cin >> choice;

        switch (choice) {
        case 1: {
            std::string searchItem;
            std::cout << "Enter the item you wish to look for: ";
            std::cin >> searchItem;
            int frequency = tracker.getFrequency(searchItem);
            std::cout << "Frequency of " << searchItem << ": " << frequency << std::endl;
            break;
        }
        case 2:
            std::cout << "List of item frequencies:\n";
            tracker.printFrequencies();
            break;
        case 3:
            std::cout << "Histogram of item frequencies:\n";
            tracker.printHistogram();
            break;
        case 4:
            tracker.saveData("frequency.dat");
            std::cout << "Data saved to frequency.dat. Exiting program.\n";
            break;
        default:
            std::cout << "Invalid choice. Please enter a number between 1 and 4.\n";
        }
    } while (choice != 4);

    return 0;
}
